### ISSUE TITLE
Recording broken on iOS Firefox/Chrome

### ISSUE THREAD

**Issue by maciej-w** [eliasmeire/mp3-mediarecorder#11]
Hi, thanks for the great work!

The example is not working on mobile, is it because mobile browser do not support this functionality?

I tested on Mozilla, Chrome and Safari on iOS.

**Comment by eliasmeire** [comment]
Hi, I tried to reproduce on those clients. iOS Safari seems to be working for me 😄.

In iOS Firefox and iOS Chrome the demo is indeed broken. I'm having trouble getting logs from those applications. Were you able to get some logs from one of those?

I tried getting Chrome DevTools remote debugging going, but no success.

**Comment by eliasmeire** [comment]
So I investigated over the weekend and `navigator.mediaDevices.getUserMedia` doesn't exist in those browsers, so the library can't work there. I added an error message to the demo to make the reason clear.

![Error message in demo for getUserMedia](https://user-images.githubusercontent.com/8850410/60499515-e9169e80-9cb8-11e9-8aa7-9e9c3b3c2c3e.PNG)

**Comment by eliasmeire** [comment]
Added the error message to the demo in d0f9390. I think that resolves this issue, let me know if something else needs fixing 👍 .
