### ISSUE TITLE
Problem after 4th recording

### ISSUE THREAD

**Issue by ktsour** [eliasmeire/mp3-mediarecorder#59]
Safari does not support more than 4 AudioContexts. Every AudioContext should be closed after each recording. You can try your live demo in Safari and you will see that it crashes on the 5th recording.
This issue is also reported in the Kagami/vmsg library:
https://github.com/Kagami/vmsg/issues/24
The same will happen in Chrome after 30 recordings.

**Comment by eliasmeire** [comment]
Hi thanks for the report, sounds like something that should be fixed.
Or if you would like to have a stab at fixing it yourself, just say the word :smile:

**Comment by ktsour** [comment]
Hi, just made a pull request for it.
